cpufreq: blu_schedutil: Fix unused warning
../kernel/sched/cpufreq_blu_schedutil.c:225:15: error: unused variable 'cpu' [-Werror,-Wunused-variable]
        unsigned int cpu;
                     ^

Signed-off-by: kyvangka1610 <kyvangka2002@gmail.com>