soc/qcom: early_random: Use random header instead of hw_random
Commit [1] has moved the declaration of add_hwgenerator_randomness()
from include/linux/hw_random.h to include/linux/random.h.

As Qualcomm's Early Random driver is still using the old header inclusion,
it's throwing the following compilation error:

../drivers/soc/qcom/early_random.c:51:3: error: implicit declaration of function 'add_hwgenerator_randomness' [-Werror,-Wimplicit-function-declaration]
                add_hwgenerator_randomness(random_buffer, bytes_received,
                ^

Replace the header hw_random.h with random.h at early_random.

[1]: 5a5ca92 ("random: pull add_hwgenerator_randomness() declaration into random.h")

Fixes: 90797c3 ("msm: Add snapshot of early random number driver")
Change-Id: Iec982c7e322493807415bf04eed71f3a035ae0d3
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>
Signed-off-by: kyvangka1610 <kyvangka2002@gmail.com>